language: php

php:
    - 5.4

before_script:
    - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
    - mv ../CakePHP-Media plugins/Media
    - chmod -R 777 ../cakephp/app/tmp
    - chmod -R 777 ../cakephp/app/webroot
    - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
    - echo "<?php
        class DATABASE_CONFIG {
        public \$test = array(
            'datasource' => 'Database/Mysql',
            'database' => 'cakephp_test',
            'host' => '127.0.0.1',
            'login' => 'travis',
            'persistent' => false,
        );
        }" > ../cakephp/app/Config/database.php

script:
    - ./lib/Cake/Console/cake test Media PluginMedia --stderr